# Autogenerated by AutoSerde (v0.0.0)
class_name _ASFileWriterTestCustomConversionObjectLoader


static func from_json_file(filepath: String) -> _ASFileWriterTestCustomConversionObject:
	var text := FileAccess.get_file_as_string(filepath)
	var obj := _ASFileWriterTestCustomConversionObjectLoader.from_json_text(text)
	return obj


static func from_json_text(text: String) -> _ASFileWriterTestCustomConversionObject:
	var json := JSON.parse_string(text)
	var obj := _ASFileWriterTestCustomConversionObjectLoader.from_json(json)
	return obj


static func from_json(json: Dictionary) -> _ASFileWriterTestCustomConversionObject:
	var obj := _ASFileWriterTestCustomConversionObject.new()
	obj.position = ASConversions.vector2_from_array(json.get("position"))
	obj.scale = ASConversions.vector2_from_array(json.get("scale"))
	return obj
