# Autogenerated by AutoSerde (v0.0.0)
class_name _ASFileWriterTestParentObjectLoader


static func from_json_file(filepath: String) -> _ASFileWriterTestParentObject:
	var text := FileAccess.get_file_as_string(filepath)
	var obj := _ASFileWriterTestParentObjectLoader.from_json_text(text)
	return obj


static func from_json_text(text: String) -> _ASFileWriterTestParentObject:
	var json := JSON.parse_string(text)
	var obj := _ASFileWriterTestParentObjectLoader.from_json(json)
	return obj


static func from_json(json: Dictionary) -> _ASFileWriterTestParentObject:
	var obj := _ASFileWriterTestParentObject.new()
	obj.inferred_serde_obj = _ASFileWriterTestOtherObjectLoader.from_json(json.get("inferred_serde_obj"))
	obj.specified_serde_obj = _ASFileWriterTestOtherObjectLoader.from_json(json.get("specified_serde_obj"))
	obj.specified_serde_array = []
	for item in json.get("specified_serde_array", []):
		var loaded_item := _ASFileWriterTestOtherObjectLoader.from_json(item)
		obj.specified_serde_array.append(loaded_item)
	return obj
