# Autogenerated by MarshalMaker (v0.0.0)
class_name _MMFileWriterTestCustomConversionObjectSaver


static func to_json_file(obj: _MMFileWriterTestCustomConversionObject, filepath: String) -> void:
	var text := _MMFileWriterTestCustomConversionObjectSaver.to_json_text(obj)
	FileAccess.open(filepath, FileAccess.WRITE).store_string(text)


static func to_json_text(obj: _MMFileWriterTestCustomConversionObject) -> String:
	var json := _MMFileWriterTestCustomConversionObjectSaver.to_json(obj)
	var text := JSON.stringify(json, "  ")
	return text


static func to_json(obj: _MMFileWriterTestCustomConversionObject) -> Dictionary:
	var result := {}
	result["position"] = MMConversions.vector2_to_array(obj.position)
	result["scale"] = MMConversions.vector2_to_dict(obj.scale)
	return result
