# Autogenerated by MarshalMaker (v0.0.0)
class_name _MMFileWriterTestCustomConversionObjectLoader


static func from_json_file(filepath: String) -> _MMFileWriterTestCustomConversionObject:
	var text := FileAccess.get_file_as_string(filepath)
	var obj := _MMFileWriterTestCustomConversionObjectLoader.from_json_text(text)
	return obj


static func from_json_text(text: String) -> _MMFileWriterTestCustomConversionObject:
	var json := JSON.parse_string(text)
	var obj := _MMFileWriterTestCustomConversionObjectLoader.from_json(json)
	return obj


static func from_json(json: Dictionary) -> _MMFileWriterTestCustomConversionObject:
	var obj := _MMFileWriterTestCustomConversionObject.new()
	obj.position = MMConversions.vector2_from_array(json.get("position"))
	obj.scale = MMConversions.vector2_from_array(json.get("scale"))
	return obj
