# Autogenerated by MarshalMaker (v0.0.0)
class_name _MMRunnerTestMultipleSerdeFilesParentObjectSaver


static func to_json_file(obj: _MMRunnerTestMultipleSerdeFilesParentObject, filepath: String) -> void:
	var text := _MMRunnerTestMultipleSerdeFilesParentObjectSaver.to_json_text(obj)
	FileAccess.open(filepath, FileAccess.WRITE).store_string(text)


static func to_json_text(obj: _MMRunnerTestMultipleSerdeFilesParentObject) -> String:
	var json := _MMRunnerTestMultipleSerdeFilesParentObjectSaver.to_json(obj)
	var text := JSON.stringify(json, "  ")
	return text


static func to_json(obj: _MMRunnerTestMultipleSerdeFilesParentObject) -> Dictionary:
	var result := {}
	result["child"] = _MMRunnerTestMultipleSerdeFilesChildObjectSaver.to_json(obj.child)
	return result
