# Autogenerated by AutoSerde (v0.0.0)
class_name _ASFileWriterTestIgnoreIncludeObjectLoader


static func from_json_file(filepath: String) -> _ASFileWriterTestIgnoreIncludeObject:
	var text := FileAccess.get_file_as_string(filepath)
	var obj := _ASFileWriterTestIgnoreIncludeObjectLoader.from_json_text(text)
	return obj


static func from_json_text(text: String) -> _ASFileWriterTestIgnoreIncludeObject:
	var json := JSON.parse_string(text)
	var obj := _ASFileWriterTestIgnoreIncludeObjectLoader.from_json(json)
	return obj


static func from_json(json: Dictionary) -> _ASFileWriterTestIgnoreIncludeObject:
	var obj := _ASFileWriterTestIgnoreIncludeObject.new()
	obj.included_var = json.get("included_var")
	return obj
