# Autogenerated by MarshalMaker (v0.0.0)
class_name _MMFileWriterTestIgnoreIncludeObjectLoader


static func from_json_file(filepath: String) -> _MMFileWriterTestIgnoreIncludeObject:
	var text := FileAccess.get_file_as_string(filepath)
	var obj := _MMFileWriterTestIgnoreIncludeObjectLoader.from_json_text(text)
	return obj


static func from_json_text(text: String) -> _MMFileWriterTestIgnoreIncludeObject:
	var json := JSON.parse_string(text)
	var obj := _MMFileWriterTestIgnoreIncludeObjectLoader.from_json(json)
	return obj


static func from_json(json: Dictionary) -> _MMFileWriterTestIgnoreIncludeObject:
	var obj := _MMFileWriterTestIgnoreIncludeObject.new()
	obj.included_var = json.get("included_var")
	return obj
