# Autogenerated bu AutoSerde
class_name _ASSaverTestSavedObjectSaver


static func to_json_file(obj: _ASSaverTestSavedObject, filepath: String) -> void:
	var text := _ASSaverTestSavedObjectSaver.to_json_text(obj)
	FileAccess.open(filepath, FileAccess.WRITE).store_string(text)


static func to_json_text(obj: _ASSaverTestSavedObject) -> String:
	var json := _ASSaverTestSavedObjectSaver.to_json(obj)
	var text := JSON.stringify(json, "  ")
	return text


static func to_json(obj: _ASSaverTestSavedObject) -> Dictionary:
	var result := {}
	
	result["a"] = obj.a
	result["pi"] = obj.pi
	result["tau"] = obj.tau
	
	return result
