# Autogenerated by MarshalMaker (v0.0.0)
class_name _MMFileWriterTestRenameObjectSaver


static func to_json_file(obj: _MMFileWriterTestRenameObject, filepath: String) -> void:
	var text := _MMFileWriterTestRenameObjectSaver.to_json_text(obj)
	FileAccess.open(filepath, FileAccess.WRITE).store_string(text)


static func to_json_text(obj: _MMFileWriterTestRenameObject) -> String:
	var json := _MMFileWriterTestRenameObjectSaver.to_json(obj)
	var text := JSON.stringify(json, "  ")
	return text


static func to_json(obj: _MMFileWriterTestRenameObject) -> Dictionary:
	var MMResult := {}
	MMResult["renamedExportVar"] = obj.renamed_export_var
	MMResult["renamedVar"] = obj.renamed_var
	MMResult["RenamedArray"] = []
	for item in obj.renamed_array:
		var saved_item := MMConversions.vector2_to_dict(item)
		MMResult["RenamedArray"].append(saved_item)
	return MMResult
