# Autogenerated by MarshalMaker (v0.0.0)
class_name _MMFileWriterTestRenameObjectLoader


static func from_json_file(filepath: String) -> _MMFileWriterTestRenameObject:
	var text := FileAccess.get_file_as_string(filepath)
	var obj := _MMFileWriterTestRenameObjectLoader.from_json_text(text)
	return obj


static func from_json_text(text: String) -> _MMFileWriterTestRenameObject:
	var json := JSON.parse_string(text)
	var obj := _MMFileWriterTestRenameObjectLoader.from_json(json)
	return obj


static func from_json(json: Dictionary) -> _MMFileWriterTestRenameObject:
	var obj := _MMFileWriterTestRenameObject.new()
	obj.renamed_export_var = json.get("renamedExportVar")
	obj.renamed_var = json.get("renamedVar")
	obj.renamed_array = []
	for item in json.get("RenamedArray", []):
		var loaded_item := MMConversions.vector2_from_dict(item)
		obj.renamed_array.append(loaded_item)
	return obj
