# Autogenerated by AutoSerde (v0.0.0)
class_name _ASFileWriterTestPrimitiveObjectSaver


static func to_json_file(obj: _ASFileWriterTestPrimitiveObject, filepath: String) -> void:
	var text := _ASFileWriterTestPrimitiveObjectSaver.to_json_text(obj)
	FileAccess.open(filepath, FileAccess.WRITE).store_string(text)


static func to_json_text(obj: _ASFileWriterTestPrimitiveObject) -> String:
	var json := _ASFileWriterTestPrimitiveObjectSaver.to_json(obj)
	var text := JSON.stringify(json, "  ")
	return text


static func to_json(obj: _ASFileWriterTestPrimitiveObject) -> Dictionary:
	var result := {}
	result["specified_string"] = obj.specified_string
	result["inferred_single_double_string"] = obj.inferred_single_double_string
	result["inferred_single_single_string"] = obj.inferred_single_single_string
	result["inferred_triple_double_string"] = obj.inferred_triple_double_string
	result["inferred_triple_single_string"] = obj.inferred_triple_single_string
	result["inferred_raw_single_double_string"] = obj.inferred_raw_single_double_string
	result["inferred_raw_single_single_string"] = obj.inferred_raw_single_single_string
	result["inferred_raw_triple_double_string"] = obj.inferred_raw_triple_double_string
	result["inferred_raw_triple_single_string"] = obj.inferred_raw_triple_single_string
	result["specified_float"] = obj.specified_float
	result["inferred_float"] = obj.inferred_float
	result["specified_int"] = obj.specified_int
	result["inferred_int"] = obj.inferred_int
	result["inferred_int_with_underscore"] = obj.inferred_int_with_underscore
	result["inferred_binary"] = obj.inferred_binary
	result["inferred_hex"] = obj.inferred_hex
	return result
