# Autogenerated by AutoSerde (v0.0.0)
class_name _ASFileWriterTestPrimitiveObjectLoader


static func from_json_file(filepath: String) -> _ASFileWriterTestPrimitiveObject:
	var text := FileAccess.get_file_as_string(filepath)
	var obj := _ASFileWriterTestPrimitiveObjectLoader.from_json_text(text)
	return obj


static func from_json_text(text: String) -> _ASFileWriterTestPrimitiveObject:
	var json := JSON.parse_string(text)
	var obj := _ASFileWriterTestPrimitiveObjectLoader.from_json(json)
	return obj


static func from_json(json: Dictionary) -> _ASFileWriterTestPrimitiveObject:
	var obj := _ASFileWriterTestPrimitiveObject.new()
	obj.specified_string = json.get("specified_string")
	obj.inferred_single_double_string = json.get("inferred_single_double_string")
	obj.inferred_single_single_string = json.get("inferred_single_single_string")
	obj.inferred_triple_double_string = json.get("inferred_triple_double_string")
	obj.inferred_triple_single_string = json.get("inferred_triple_single_string")
	obj.inferred_raw_single_double_string = json.get("inferred_raw_single_double_string")
	obj.inferred_raw_single_single_string = json.get("inferred_raw_single_single_string")
	obj.inferred_raw_triple_double_string = json.get("inferred_raw_triple_double_string")
	obj.inferred_raw_triple_single_string = json.get("inferred_raw_triple_single_string")
	obj.specified_float = json.get("specified_float")
	obj.inferred_float = json.get("inferred_float")
	obj.specified_int = json.get("specified_int")
	obj.inferred_int = json.get("inferred_int")
	obj.inferred_int_with_underscore = json.get("inferred_int_with_underscore")
	obj.inferred_binary = json.get("inferred_binary")
	obj.inferred_hex = json.get("inferred_hex")
	return obj
