# Autogenerated by AutoSerde (v0.0.0)
class_name _ASFileWriterTestSavedObjectLoader


static func from_json_file(filepath: String) -> _ASFileWriterTestSavedObject:
	var text := FileAccess.get_file_as_string(filepath)
	var obj := _ASFileWriterTestSavedObjectLoader.from_json_text(text)
	return obj


static func from_json_text(text: String) -> _ASFileWriterTestSavedObject:
	var json := JSON.parse_string(text)
	var obj := _ASFileWriterTestSavedObjectLoader.from_json(json)
	return obj


static func from_json(json: Dictionary) -> _ASFileWriterTestSavedObject:
	var obj := _ASFileWriterTestSavedObject.new()
	obj.inferred_string = json.get("inferred_string")
	obj.inferred_float = json.get("inferred_float")
	obj.inferred_int = json.get("inferred_int")
	obj.inferred_binary = json.get("inferred_binary")
	obj.inferred_hex = json.get("inferred_hex")
	obj.specified_string = json.get("specified_string")
	obj.specified_float = json.get("specified_float")
	obj.specified_int = json.get("specified_int")
	obj.included_var = json.get("included_var")
	obj.inferred_serde_obj = _ASFileWriterTestOtherObjectLoader.from_json(json.get("inferred_serde_obj"))
	obj.specified_serde_obj = _ASFileWriterTestOtherObjectLoader.from_json(json.get("specified_serde_obj"))
	obj.specified_serde_array = []
	for item in json.get("specified_serde_array", []):
		var loaded_item := _ASFileWriterTestOtherObjectLoader.from_json(item)
		obj.specified_serde_array.append(loaded_item)
	return obj
