class_name MMSaverFileWriter
extends MMMarshallerFileWriter


func _get_template() -> String:
	return r"""
# Autogenerated by MarshalMaker ({marshal_maker_version})
class_name {type}Saver


static func to_json_file(obj: {type}, filepath: String) -> void:
	var text := {type}Saver.to_json_text(obj)
	FileAccess.open(filepath, FileAccess.WRITE).store_string(text)


static func to_json_text(obj: {type}) -> String:
	var json := {type}Saver.to_json(obj)
	var text := JSON.stringify(json, "  ")
	return text


static func to_json(obj: {type}) -> Dictionary:
	var MMResult := {}
{primitive_conversions}
{simple_conversions}
{simple_array_conversions}
{serde_conversions}
{serde_array_conversions}
	return MMResult
""".strip_edges()

func _get_field_conversion_factory(field_data: MMObjectTokensFieldData) -> MMSerdeFieldConversionFactory:
	return MMSaverFieldConversionFactory.new(field_data, _context)
