class_name ASSaverFileWriter
extends ASSerdeFileWriter


func _get_template() -> String:
	return r"""
# Autogenerated by AutoSerde ({auto_serde_version})
class_name {type}Saver


static func to_json_file(obj: {type}, filepath: String) -> void:
	var text := {type}Saver.to_json_text(obj)
	FileAccess.open(filepath, FileAccess.WRITE).store_string(text)


static func to_json_text(obj: {type}) -> String:
	var json := {type}Saver.to_json(obj)
	var text := JSON.stringify(json, "  ")
	return text


static func to_json(obj: {type}) -> Dictionary:
	var result := {}
{primitive_conversions}
{simple_conversions}
{simple_array_conversions}
{serde_conversions}
{serde_array_conversions}
	return result
""".strip_edges()

func _get_field_conversion_factory(field_data: ASObjectTokensFieldData) -> ASSerdeFieldConversionFactory:
	return ASSaverFieldConversionFactory.new(field_data, _context)
